name: Build README
on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
        with:
          # necessary for github-action-til-autoformat-readme
          fetch-depth: 0
      - name: Autoformat README
        uses: cflynn07/github-action-til-autoformat-readme@1.1.0
        with:
          description: |
            iOS 기본앱들을 여러가지 방법으로 만들어보면서 기술습득을 위한 레포지토리입니다. ✨
          footer: |
            [1]: https://simonwillison.net/2020/Apr/20/self-rewriting-readme/
            [2]: https://github.com/jbranchaud/til
          list_most_recent: 5 # optional, lists most recent TILS below description
          date_format: '2020 Jan 15:04' # optional, must align to https://golang.org/pkg/time/#Time.Format
